# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  file:
    name: delogs.log

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  profiles:
#    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

rtsp:
#  url: E:/视频/VID_20141122_212032.mp4
#  url: E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\01-03-Basic Recipe for Machine Learning.mp4
#  url: E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\01-03-Basic Recipe.mp4
#  url: E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\02-11-Yuanqing Lin interview.mp4
#  url: E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\01-04-Regularization bak.mp4

#  url: E:\video\1.mp4
#  url: rtsp://127.0.0.1:8554/video
#  url: http://192.168.18.76:4747/video
#  url: http://10.0.0.5:4747/video
  url: http://10.0.0.5:4747/video
  mot_url: 192.168.2.102

#  url: ‪E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\01-04-Regularization bak.mp4
#  url: ‪E:‪/01-03-Basic Recipe for Machine Learning.mp4
#  url: E:\
#  url: ‪E:\Andrew Ng深度学习\课程部分\deeplearning.ai_02_Improving Deep Neural Networks\01-04-Regularization bak.mp4
  transport:
    type: udp
#    type: tcp